### ISSUE TITLE
Offset and limit options?

### ISSUE THREAD

**Issue by jorgemanrubia** [jensarps/IDBWrapper#47]
Hi,

Is there a way to set a `limit`/`offset` when using the `query` method? It seems that the only way to configure the query is `makeKeyRange `, but unless I am missing something it doesn't let you set a offset or limit.

Thanks

Regards

**Comment by jensarps** [comment]
Pagination via limit/offset available in [version 1.5](https://github.com/jensarps/IDBWrapper/tree/v1.5), closing this.
