### ISSUE TITLE
thinner npm version

### ISSUE THREAD

**Issue by kessler** [jensarps/IDBWrapper#52]
Hi,

Would it be possible to publish this module to npm without the closure compiler jar and the examples?
I tried looking around but didn't see where closure is used.. maybe I missed it.

Thanks

Yaniv

**Comment by jokeyrhyme** [comment]
You can use the `files` option in package.json to control which files are to be distributed downstream. You can also use a .npmignore file if that makes more sense.

https://docs.npmjs.com/files/package.json

>The "files" field is an array of files to include in your project. If you name a folder in the array, then it will also include the files inside that folder. (Unless they would be ignored by another rule.)

>You can also provide a ".npmignore" file in the root of your package, which will keep files from being included, even if they would be picked up by the files array. The ".npmignore" file works just like a ".gitignore".

**Comment by kessler** [comment]
Good point :)
