### ISSUE TITLE
support null values

### ISSUE THREAD

**Issue by mcollina** [jensarps/IDBWrapper#63]
Null values can be successfully inserted via `put()`.
However, in `get()`, there is no difference between a missing key and one with value `null`.

Do you think it is feasible to add an API to differentiate, or better add a second parameter to the `get` `onSuccess` callback to differentiate in this particular case?

This is needed to support the latest leveldown interface https://github.com/maxogden/level.js/pull/41

**Comment by jensarps** [comment]
@mcollina Thanks for reporting.

According to the spec, a missing key will be returned as `undefined` by `get()`. In a quick check, at least Chrome does this accordingly – `data` is indeed `undefined` here: https://github.com/jensarps/IDBWrapper/blob/master/test/idbwrapper_spec.js#L98

Did you test this? If so, in which browser did you get `null` for a missing key?

**Comment by jensarps** [comment]
Closing this, as IDBWrapper supports null values (as browsers do). For details, see discussion over at maxogden/level.js#41 and @timkuijsten's work there.
