### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by khurramraheel** [jensarps/IDBWrapper#69]
The library doesn't seem to work in IE 11.

**Comment by jensarps** [comment]
@khurramraheel Can you describe what the exact issue is that you run into? 

Tests all pass on IE11 (except of course for the ones that IE11 can't run, i.e. multiEntry and compound index).

**Comment by khurramraheel** [comment]
I was using wrong key-pair when saving values. In Chrome, it worked but not in IE.

**Comment by jensarps** [comment]
Thanks for the update, great that it worked out in the end :) However, I'd be interested to know what it was that worked in Chrome and not on IE, so please feel free to share it here.
