### ISSUE TITLE
Doesn't appear to work anymore

### ISSUE THREAD

**Issue by oising** [jensarps/IDBWrapper#70]
I went to the examples site and it failed to save any information. Errors appear in the chrome console log concerning the native API. I'm on Chrome 49 desktop.

**Comment by jensarps** [comment]
Just tried with Chrome 49, and it works fine for me. 

To further investigate, could you please share the exact error message that you get? Also, what was the exact URL you were visiting? Was it http://jensarps.github.io/IDBWrapper/example/ ?

Thanks!

**Comment by oising** [comment]
It was on http://jensarps.github.io/IDBWrapper/example/basic/ but I just realized that I used a letter instead of a number for a key --  `Uncaught DataError: Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path yielded a value that is not a valid key.` was in the browser console. I guess I should have paid more attention to the label, but a little validation might help too ;)

**Comment by jensarps** [comment]
Great that it worked for you in the end – and, yeah, I probably should add a validation to that example :)
