### ISSUE TITLE
IndexedDBShim Support?

### ISSUE THREAD

**Issue by ballenjr** [jensarps/IDBWrapper#73]
I am getting this error(Error: undefined is not an object (evaluating 'this.store.query')) from https://github.com/mWater/minimongo/blob/master/dist/minimongo.js#L832

When I install https://github.com/axemclion/IndexedDBShim

I see here https://github.com/jensarps/IDBWrapper/blob/master/idbstore.js#L47 that this shim should be supported?

I am working on iOS WKWebView. It is a cordova app and all the research that I can turn up says that iOS has botched the implementation bad. But the shim claims to be able to fix it. And it does get me past the original error from within minimongo which was db = undefined.

https://github.com/axemclion/IndexedDBShim/issues/244

So I originally created an issue in the shim repo thinking that installing it broke something with IDBStore making the query method disappear. But then I got digging deeper and saw that IDBWrapper seems to be intending to coexist with the shim as is.

Is there a specific version that works better? Or is this a real bug? Or is the assumed support not really there? Any suggestions otherwise?

**Comment by ballenjr** [comment]
Would it make any kind of sense to change this https://github.com/jensarps/IDBWrapper/blob/master/idbstore.js#L133 to this.implementation = availableImplementations[availableImplementations.length - 1];

Presumably choosing the shim...

**Comment by ballenjr** [comment]
Just discovered that I was suppressing the real error which was a DOM Security Error having something to do with the call to openDatabase from within the shim createSysDB method.

**Comment by ballenjr** [comment]
https://github.com/Telerik-Verified-Plugins/WKWebView/issues/11 says that WebSQL is disabled. I get the same error without the shim trying to openDatabase even with the minimum free quota. So maybe they are right.

**Comment by jensarps** [comment]
Hi @ballenjr,

WKWebView is a beast… See also this gist: https://gist.github.com/nolanlawson/08eb857c6b17a30c1b26#wkwebview

The following won't help you for your issue, but just to let you know: You can define your own implementation preference, e.g. to make IDBWrapper prefer the shim: https://github.com/jensarps/IDBWrapper/wiki/Usage#defining-implementation-preference-aka-make-idbwrapper-use-the-shim

**Comment by ballenjr** [comment]
Thanks for the info. I will check it out.

**Comment by ballenjr** [comment]
That's good that websql was enabled. But it was always a bad option for me
as long as quotas were enabled. It seems, according to that bug, that
quotas weren't implemented until that fix. Which really limits the
usefulness of websql in an app. I was only interested in its speed gains
over the key value model of local storage.

I still really need indexeddb in the end. My understanding is that there is
no quota to speak of. But I am also using a minimongo wrapper. So that
complicates the point of entry into idbstore. As it relates to using the
config option that you reference. But I am reasonably sure that I did force
it somewhere else, though I had another idea that I wanted to try
eventually. I want to try to find a way to bypass the broken webkit
implementation altogether and use a native shim to adapt everything.

There is a plugin but it didn't work before. Maybe now that websql is
enabled. And hopefully using the plugin will bypass the quota
implementation. Though I am skeptical.

Any word when apple will release the fix? I'll give it a shot.

**Comment by jensarps** [comment]
No idea when Apple will release the changes to WKWebView, but given that the commit is only three weeks old ([issue](https://bugs.webkit.org/show_bug.cgi?id=156928)/[commit](http://trac.webkit.org/changeset/199901)), I'd say it might take some time… :(

**Comment by ballenjr** [comment]
Ya, I figured. Guess I'll just check the future releases as they come out.
