### ISSUE TITLE
'Object store couldn't be created' when opening two times the same page

### ISSUE THREAD

**Issue by jackstrapp** [jensarps/IDBWrapper#74]
Hello, 

I have an issue on FF 47 (at least).  When we open two times the same page using IDBWrapper, 
the database seems to corrupt itself. I get this error : 'Object store couldn't be created' even after rebooting FF. 

To solve the problem i must clear IDB files in firefox folders. :(

Do you have an  idea of what can be the problem? 

Thank you very much.

**Comment by jayfunk** [comment]
What is it you are opening two times? Could you give an example snippet that will recreate the issue in FF?

**Comment by jackstrapp** [comment]
I don't have time to make a plunk for now, I'll try to do it tomorow.

Thank you

**Comment by jackstrapp** [comment]
Sorry for that, 

we thought we isolated the issue but we cannot anymore reproduce it... 

I'll come back if it starts again and if we isolate properly the problem.

for information: the bug showed up when we were reseting the databases (by using IDBStore.deleteDatabase).

Thank you.
