### ISSUE TITLE
IE11 chokes on binary keys

### ISSUE THREAD

**Issue by mvayngrib** [jensarps/IDBWrapper#77]
Not sure if you've run into this but put() with a Uint8Array key results in a DataError

**Comment by jensarps** [comment]
Thanks for the heads-up!

Binary keys were part of the 2.0 spec of IndexedDB, sad to see IE11 doesn't support that feature (Chrome had it in 2014 already). I didn't check, but I assume Safari doesn't either…

However, IDBWrapper doesn't touch given keys, and I don't want to change that, so nothing I can do about it. Still, thanks for reporting!
