### ISSUE TITLE
qq re optimizing queries or partition object stores

### ISSUE THREAD

**Issue by isao** [jensarps/IDBWrapper#82]
Hello Jens,

Thanks very much for your work on IDBWrapper! (This is not a bug report...)

I'm trying to use it for a large set (up to around 800K) of smallish time-based records. My most important query is to get records whose start/end fall in a range. I use, for example, a StartTime index, and filter on EndTime... and this can get quite slow.

I was wondering if it would be feasible to use IDBWrapper, to partition the data into separate object stores. Currently it looks like there is only one store per database, unless I'm missing something. Any advice appreciated.

Thanks again, and best regards,

Isao

**Comment by jensarps** [comment]
Thanks @isao! And, sorry for the late answer.

The one-store-per-db rule that IDBWrapper uses makes it unlikely that using different object stores would give you a perf improvement, as you wouldn't be able to open multiple stores in one transaction. So, creating KeyRanges and making sure there's an index for every property in your KeyRange is your only option, I guess.

I mean, you could still give it a try with, e.g., two databases and see how it goes – you never know :)

Another option could be to offload the whole database work into a webworker; that will probably give you an actual improvement during querying the store, but you'd have to message back the results to the main thread. That's what I'd probably try.

Let me know how it goes!

Cheers,
Jens

**Comment by isao** [comment]
Thanks Jens! Yes, I'm using a web worker, and some purpose-built IndexedDB code now.  I've partitioned over stores, but haven't seen the perf improvement I was hoping for yet (on a constrained device using Chromium 51).  Do you know if transactions over two stores would be slower than queries on two databases? Nm, I don't mean to beg for free consultation.

I've really appreciated IDBWrapper and the documentation. Cheers!

**Comment by jensarps** [comment]
No worries :)

Bummer that doing the queries in a worker didn't come with a perf improvement. Regarding the transactions: I'd assume that opening two stores in one transaction on one database should be way better than running two transaction on two distinct databases – but, that's just an assumption, you'd have to actually do that and compare the numbers to be sure.
